# 01 — Data Cleaning and Initial Exploration

This notebook loads the raw loan dataset, inspects its structure, handles missing values, fixes data types, and prepares a clean dataset for EDA and modeling.

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

# Loading the dataset
df = pd.read_csv("C:/Users/user/Loan_default_predictor/data/raw/sample/Loan_default_Sample.csv")
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

### Dataset Preview
The table below shows the first few rows of the raw dataset.

In [15]:

#understanding the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   LoanID          4999 non-null   str
 1   Age             4999 non-null   int64
 2   Income          4999 non-null   int64
 3   LoanAmount      4999 non-null   int64
 4   CreditScore     4999 non-null   int64
 5   MonthsEmployed  4999 non-null   int64
 6   NumCreditLines  4999 non-null   int64
 7   InterestRate    4999 non-null   float64
 8   LoanTerm        4999 non-null   int64
 9   DTIRatio        4999 non-null   float64
 10  Education       4999 non-null   str
 11  EmploymentType  4999 non-null   str
 12  MaritalStatus   4999 non-null   str
 13  HasMortgage     4999 non-null   str
 14  HasDependents   4999 non-null   str
 15  LoanPurpose     4999 non-null   str
 16  HasCoSigner     4999 non-null   str
 17  Default         4999 non-null   int64
dtypes: float64(2), int64(8), str(8)
memory usage: 703.1 KB

In [16]:
df.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,4999.000000,4999.000000,4999.000000,4999.000000,4999.000000,4999.000000,4999.000000,4999.000000,4999.000000,4999.000000
mean,43.586117,82714.654331,128621.769154,575.599120,58.939588,2.494899,13.447069,36.266453,0.501984,0.117223
std,14.920200,39177.543816,70265.433699,158.136138,34.473284,1.123401,6.624820,17.038789,0.229135,0.321719
min,18.000000,15008.000000,5020.000000,300.000000,0.000000,1.000000,2.010000,12.000000,0.100000,0.000000
25%,31.000000,49097.000000,67764.500000,438.000000,28.000000,1.000000,7.665000,24.000000,0.310000,0.000000
50%,43.000000,82363.000000,129042.000000,578.000000,59.000000,2.000000,13.630000,36.000000,0.510000,0.000000
75%,56.000000,116685.500000,188907.000000,707.000000,88.000000,4.000000,19.195000,48.000000,0.700000,0.000000
max,69.000000,149975.000000,249863.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

### Summary
- `df.info()` shows column names, data types, and missing values.
- `df.describe()` provides summary statistics for numeric and categorical variables.

In [17]:
# Checking missing values
df.isna().sum().sort_values(ascending=False)

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

### The dataset has:

- Categorical columns stored as str
- Binary Yes/No columns stored as str
- Numeric columns already correct  
We convert:
- Education → category
- EmploymentType → category
- MaritalStatus → category
- LoanPurpose → category
- HasMortgage, HasDependents, HasCoSigner → binary 0/1

In [18]:
# Converting categorical columns to category data type
categorical_cols = [
    'Education','EmploymentType','MaritalStatus','LoanPurpose'
]

for col in categorical_cols:
    df[col] = df[col].astype('category')

In [19]:
# Converting Yes/No columns to binary
binary_cols = ['HasMortgage','HasDependents','HasCoSigner']

for col in binary_cols:
    df[col] = df[col].map({'Yes':1, 'No':0})

In [20]:
# Dropping duplicates
df = df.drop_duplicates()

In [21]:
# saving the cleaned dataset
df.to_csv("C:/Users/user/Loan_default_predictor/data/clean/Loan_default_clean.csv", index=False)

### Cleaned Dataset Saved
The cleaned dataset has been saved to `data/processed/Loan_default_clean.csv` for use in the EDA notebook.